version: '2'
services:
  cartemaster:
    image:
      mazagroup/pentaho:pdi-ce
    ports:
      - "8181:8181"
    environment:
      - PDI_RELEASE=6.1
      - PDI_VERSION=6.1.0.1-196
      - CARTE_PORT=8181
      - CARTE_IS_MASTER=Y
      - CARTE_INCLUDE_MASTERS=N
    labels:
      - "constraint:bi.node.service.layer==pdi"
  carteworker:
    image:
      mazagroup/pentaho:pdi-ce
    ports:
      - "8182"
    environment:
      - PDI_RELEASE=6.1
      - PDI_VERSION=6.1.0.1-196
      - CARTE_PORT=8182
      - CARTE_IS_MASTER=N
      - CARTE_INCLUDE_MASTERS=Y
      - CARTE_MASTER_HOSTNAME=cartemaster
      - CARTE_MASTER_PORT=8181
    labels:
      - "constraint:bi.node.service.layer==pdi"
    links:
      - cartemaster
networks:
  default:
    external:
      name: pentaho-overlay-network
