version: '2'


services:

  unit:
    image: golang:1.6
    volumes:
      - .:/usr/src/myapp
      - /tmp/go:/go
    command: bash -c "cd /usr/src/myapp && go get -d -v -t && go test --cover --run UnitTest ./... && go build -v -o docker-flow-proxy"

  staging-dep:
    image: vfarcic/docker-flow-proxy
    environment:
      - CONSUL_ADDRESS=${HOST_IP}:8500
      - PROXY_INSTANCE_NAME=proxy-test-instance
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./test_configs/:/test_configs/
    depends_on:
      - staging-service-proxy
      - consul
      - registrator
      - app-1
      - app-2
      - app-3
      - app-4

  staging-service-proxy:
    image: vfarcic/docker-flow-proxy
    environment:
      - PROXY_INSTANCE_NAME=proxy-service-test-instance
      - MODE=swarm
    ports:
      - 9000:80
      - 9080:8080
    volumes:
      - ./test_configs/:/test_configs/

  staging:
    image: vfarcic/docker-flow-proxy-test
    volumes:
      - .:/usr/src/myapp
      - /tmp/go:/go
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_IP=${HOST_IP}
      - CONSUL_IP=${HOST_IP}
    working_dir: /usr/src/myapp
    command: bash -c "go get -d -v -t && go test -v --run IntegrationTest ./..."

  staging-general:
    extends:
      service: staging
    command: bash -c "cd /usr/src/myapp && go get -d -v -t && go test -v --run GeneralIntegrationTest ./..."

  staging-service:
    extends:
      service: staging
    command: bash -c "cd /usr/src/myapp && go get -d -v -t && go test -v --run ServiceIntegrationTest ./..."

  production:
    extends:
      service: staging

  consul:
    image: progrium/consul
    ports:
      - 8500:8500
      - 8301:8301
      - 8300:8300
    command: -server -bootstrap

  registrator:
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -ip ${HOST_IP} consul://${HOST_IP}:8500
    depends_on:
      - consul

  app-1:
    image: vfarcic/docker-flow-proxy
    environment:
      CONSUL_ADDRESS: ${HOST_IP}:8500
      SERVICE_8080_NAME: test-service
    ports:
      - 8080
    depends_on:
      - consul

  app-2:
    image: vfarcic/docker-flow-proxy
    environment:
      CONSUL_ADDRESS: ${HOST_IP}:8500
      SERVICE_8080_NAME: test-service
    ports:
      - 8080
    depends_on:
      - consul

  app-3:
    image: vfarcic/docker-flow-proxy
    environment:
      CONSUL_ADDRESS: ${HOST_IP}:8500
      SERVICE_8080_NAME: test-service
    ports:
      - 8080
    depends_on:
      - consul

  app-4:
    image: vfarcic/docker-flow-proxy
    environment:
      CONSUL_ADDRESS: ${HOST_IP}:8500
      SERVICE_8080_NAME: test-other-service
    ports:
      - 8080
    depends_on:
      - consul