- name: Container is running
  docker:
    name: consul
    image: progrium/consul
    state: running
    ports:
      - 8500:8500
      - 8301:8301
      - 8300:8300
    hostname: "{{ ansible_hostname }}"
    command: -advertise {{ facter_ipaddress_eth1 }} -server {{ consul_extra }}
