home: /data/jenkins
main_job_src: service-workflow-config.xml
jenkins_port: 8080

configs: [
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml", mode: "0777" },
  { src: "docker-node-config.xml", dir: "/data/jenkins/nodes/docker", file: "config.xml", mode: "0777" },
]

jobs:
  - "deploy-to-swarm-without-proxy"
  - "deploy-to-swarm-with-proxy"
  - "scale-to-swarm-with-proxy"

plugins:
  - git
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
