- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present

- name: Debian Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes

- name: Debian python-pip is present
  apt: name=python-pip state=present

- name: Debian docker-py is present
  pip:
    name: docker-py
    version: 1.6.0
    state: present

- name: Debian files are present
  template:
    src: docker.cfg
    dest: /etc/default/docker
  register: copy_result

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed
